/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancotec.ventanas;

import bancotec.ConfiguracionInicial;
import bancotec.impl.Ventanilla;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;

/**
 *
 * @author ANDRES MS
 */
public class Estadisticas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboVentanilla = new javax.swing.JComboBox();
        ComboUsuario = new javax.swing.JComboBox();
        ComboHora = new javax.swing.JComboBox();
        ComboVentanillaEspecifica = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TextVentanilla = new javax.swing.JTextField();
        TextVentanillaE = new javax.swing.JTextField();
        TextUsuario = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        NumeroVentanilla = new javax.swing.JComboBox();
        NumeoVentanilla1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setTitle("ESTADISTICAS");

        ComboVentanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboVentanillaActionPerformed(evt);
            }
        });

        ComboUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Regular", "Corporativo", "Mujer Embarazada", "Adulto Mayor", "Discapacitado" }));
        ComboUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ComboUsuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ComboUsuarioMousePressed(evt);
            }
        });
        ComboUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboUsuarioActionPerformed(evt);
            }
        });

        ComboHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboHoraActionPerformed(evt);
            }
        });

        ComboVentanillaEspecifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboVentanillaEspecificaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tiquetes por Ventanilla");

        jLabel2.setText("Tiquetes por ventanilla especifica");

        jLabel3.setText("Tiquetes por Usuario");

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TextVentanilla.setEnabled(false);
        TextVentanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextVentanillaActionPerformed(evt);
            }
        });

        TextVentanillaE.setEnabled(false);
        TextVentanillaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextVentanillaEActionPerformed(evt);
            }
        });

        TextUsuario.setEnabled(false);
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });

        jTextField5.setEnabled(false);

        NumeroVentanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroVentanillaActionPerformed(evt);
            }
        });

        NumeoVentanilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeoVentanilla1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Promedio de tiempo por ventanilla Esp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(ComboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboVentanillaEspecifica, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NumeroVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TextVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NumeoVentanilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextVentanillaE, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboVentanillaEspecifica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextVentanillaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeoVentanilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroVentanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboVentanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVentanillaActionPerformed
        // TODO add your handling code here:
        String temp = String.valueOf(ComboVentanilla.getSelectedItem());

        for (int recorriendo = 0; recorriendo < ConfiguracionInicial.ArregloVentanillas.size(); recorriendo++) {
            Ventanilla Ventan = (Ventanilla) ConfiguracionInicial.ArregloVentanillas.get(recorriendo);
            if (Ventan.Nombre() == temp) {
                TextVentanilla.setText(String.valueOf(Ventan.ClientesPasadosCaja));
            }
            System.out.println("Clientes pasados " + Ventan.ClientesPasadosCaja);
        }

    }//GEN-LAST:event_ComboVentanillaActionPerformed

    private void ComboUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboUsuarioActionPerformed
        // TODO add your handling code here:
        if (ComboUsuario.getSelectedItem() == "Regular") {
            TextUsuario.setText(String.valueOf(Quiosco.numeroR));
        }
        if (ComboUsuario.getSelectedItem() == "Corporativo") {
            TextUsuario.setText(String.valueOf(Quiosco.numeroC));
        }
        if (ComboUsuario.getSelectedItem() == "Mujer Embarazada") {
            TextUsuario.setText(String.valueOf(Quiosco.numeroE));
        }
        if (ComboUsuario.getSelectedItem() == "Adulto Mayor") {
            TextUsuario.setText(String.valueOf(Quiosco.numeroM));
        }
        if (ComboUsuario.getSelectedItem() == "Discapacitado") {
            TextUsuario.setText(String.valueOf(Quiosco.numeroD));
        }
    }//GEN-LAST:event_ComboUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ComboHora.removeAllItems();
        ComboVentanilla.removeAllItems();
        ComboVentanillaEspecifica.removeAllItems();
        ComboUsuario.removeAllItems();
        NumeoVentanilla1.removeAllItems();
        NumeroVentanilla.removeAllItems();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboUsuarioMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboUsuarioMouseClicked

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void ComboUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboUsuarioMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboUsuarioMouseExited

    private void ComboUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboUsuarioMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboUsuarioMousePressed

    private void TextVentanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVentanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVentanillaActionPerformed

    private void ComboVentanillaEspecificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboVentanillaEspecificaActionPerformed
        // TODO add your handling code here:
        String NombreVentanilla = (String) ComboVentanillaEspecifica.getSelectedItem();
        int i = 0;
        int NumeroVentanillas = 0;
        Ventanilla Ventana;
        while (i < ConfiguracionInicial.ArregloVentanillas.size()) {
            Ventana = (Ventanilla) ConfiguracionInicial.ArregloVentanillas.get(i);
            if (Ventana.Nombre().equals(NombreVentanilla)) {
                NumeoVentanilla1.removeAllItems();
                NumeroVentanillas = Ventana.VentanillasDisponibles.length;
                i = ConfiguracionInicial.ArregloVentanillas.size();
            } else {
                i++;
            }
        }
        int var = 1;
        while (var <= NumeroVentanillas) {
            NumeoVentanilla1.addItem(var);
            var++;
        }
    }//GEN-LAST:event_ComboVentanillaEspecificaActionPerformed

    private void TextVentanillaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextVentanillaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextVentanillaEActionPerformed

    private void NumeroVentanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroVentanillaActionPerformed

    }//GEN-LAST:event_NumeroVentanillaActionPerformed

    private void NumeoVentanilla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeoVentanilla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeoVentanilla1ActionPerformed

    private void ComboHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboHoraActionPerformed
        String NombreVentanilla = (String) ComboHora.getSelectedItem();
        int i = 0;
        int NumeroVentanillas = 0;
        Ventanilla Ventana;
        while (i < ConfiguracionInicial.ArregloVentanillas.size()) {
            Ventana = (Ventanilla) ConfiguracionInicial.ArregloVentanillas.get(i);
            if (Ventana.Nombre().equals(NombreVentanilla)) {
                NumeroVentanilla.removeAllItems();
                NumeroVentanillas = Ventana.VentanillasDisponibles.length;
                i = ConfiguracionInicial.ArregloVentanillas.size();
            } else {
                i++;
            }
        }
        int var = 1;
        while (var <= NumeroVentanillas) {
            NumeroVentanilla.addItem(var);
            var++;
        }
    }//GEN-LAST:event_ComboHoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox ComboHora;
    public static javax.swing.JComboBox ComboUsuario;
    public static javax.swing.JComboBox ComboVentanilla;
    public static javax.swing.JComboBox ComboVentanillaEspecifica;
    public static javax.swing.JComboBox NumeoVentanilla1;
    public static javax.swing.JComboBox NumeroVentanilla;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JTextField TextVentanilla;
    private javax.swing.JTextField TextVentanillaE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
