/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bancotec.ventanas;

import bancotec.ConfiguracionInicial;
import bancotec.impl.Cliente;
import bancotec.VentanaPrincipal;
import bancotec.impl.SendMailTLS;
import bancotec.impl.Ventanilla;
import static bancotec.ventanas.Administracion.Combo_EliminarVentanillas;
import static bancotec.ventanas.Ventanillas.NumeroVentanillaCB;
import static bancotec.ventanas.Ventanillas.TipoVentanillaCB;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDRES MS
 */
public class Quiosco extends javax.swing.JInternalFrame {

    public static int numeroR = 0;
    public static int numeroC = 0;
    public static int numeroE = 0;
    public static int numeroM = 0;
    public static int numeroD = 0;
    /**
     * Creates new form Quiosco
     */
    Ventanilla Ventanilla;

    public Quiosco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextNombre = new javax.swing.JTextField();
        TextCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RegularCheck = new javax.swing.JRadioButton();
        CorporativoCheck = new javax.swing.JRadioButton();
        EmbarazadaCheck = new javax.swing.JRadioButton();
        MayorCheck = new javax.swing.JRadioButton();
        DiscapacitadoCheck = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        TipoVentanillaComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        AceptarQuiosco = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();

        setInheritsPopupMenu(true);
        setPreferredSize(new java.awt.Dimension(478, 284));

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });

        TextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorreoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Correo Electronico");

        RegularCheck.setText("Regular");
        RegularCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegularCheckActionPerformed(evt);
            }
        });

        CorporativoCheck.setText("Corporativo");
        CorporativoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorporativoCheckActionPerformed(evt);
            }
        });

        EmbarazadaCheck.setText("Mujer Embarazada");
        EmbarazadaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmbarazadaCheckActionPerformed(evt);
            }
        });

        MayorCheck.setText("Adulto Mayor");
        MayorCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MayorCheckActionPerformed(evt);
            }
        });

        DiscapacitadoCheck.setText("Discapacitado");
        DiscapacitadoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscapacitadoCheckActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo de Ventanilla");

        TipoVentanillaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoVentanillaComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Cliente");

        AceptarQuiosco.setText("Aceptar");
        AceptarQuiosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarQuioscoActionPerformed(evt);
            }
        });

        jLabel5.setText("Numero de Celular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(TextNombre)
                                    .addComponent(TipoVentanillaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCel)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MayorCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CorporativoCheck)
                                        .addGap(18, 18, 18)
                                        .addComponent(EmbarazadaCheck))
                                    .addComponent(DiscapacitadoCheck)))
                            .addComponent(RegularCheck)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)))
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AceptarQuiosco)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TipoVentanillaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegularCheck)
                    .addComponent(CorporativoCheck)
                    .addComponent(EmbarazadaCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MayorCheck)
                    .addComponent(DiscapacitadoCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AceptarQuiosco)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoActionPerformed

    private void RegularCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegularCheckActionPerformed
        CorporativoCheck.setSelected(false);
        EmbarazadaCheck.setSelected(false);
        MayorCheck.setSelected(false);
        DiscapacitadoCheck.setSelected(false);
    }//GEN-LAST:event_RegularCheckActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void CorporativoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorporativoCheckActionPerformed
        RegularCheck.setSelected(false);
        EmbarazadaCheck.setSelected(false);
        MayorCheck.setSelected(false);
        DiscapacitadoCheck.setSelected(false);
    }//GEN-LAST:event_CorporativoCheckActionPerformed

    private void EmbarazadaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmbarazadaCheckActionPerformed
        RegularCheck.setSelected(false);
        CorporativoCheck.setSelected(false);
        MayorCheck.setSelected(false);
        DiscapacitadoCheck.setSelected(false);
    }//GEN-LAST:event_EmbarazadaCheckActionPerformed

    private void MayorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MayorCheckActionPerformed
        RegularCheck.setSelected(false);
        EmbarazadaCheck.setSelected(false);
        CorporativoCheck.setSelected(false);
        DiscapacitadoCheck.setSelected(false);
    }//GEN-LAST:event_MayorCheckActionPerformed

    private void DiscapacitadoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscapacitadoCheckActionPerformed
        RegularCheck.setSelected(false);
        EmbarazadaCheck.setSelected(false);
        MayorCheck.setSelected(false);
        CorporativoCheck.setSelected(false);
    }//GEN-LAST:event_DiscapacitadoCheckActionPerformed

    private void AceptarQuioscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarQuioscoActionPerformed

        if (TextNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre");
        } else if (TextCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el correo");
        } else if (txtCel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el celular");
        } else if (TipoVentanillaComboBox.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "No hay cajas o no ha seleccionado ninguna");
        } else if ((RegularCheck.isSelected() == false) && (CorporativoCheck.isSelected() == false) && (EmbarazadaCheck.isSelected() == false) && (MayorCheck.isSelected() == false) && (DiscapacitadoCheck.isSelected() == false)) {
            JOptionPane.showMessageDialog(null, "Selecciones tipo de cliente");
        } else {

            String Tipo;
            String Nombre = TextNombre.getText();
            String Correo = TextCorreo.getText();
            String Celular = txtCel.getText();
            String Ventanilla = (String) TipoVentanillaComboBox.getSelectedItem();

            int i = 0;
            Ventanilla Ventana = new Ventanilla();

            while (i < ConfiguracionInicial.ArregloVentanillas.size()) {
                Ventana = (Ventanilla) ConfiguracionInicial.ArregloVentanillas.get(i);
                if (Ventana.Nombre().equals(Ventanilla)) {
                    Ventana.PasaCliente();
                    i = ConfiguracionInicial.ArregloVentanillas.size();
                } else {
                    i++;
                }
            }
            if (RegularCheck.isSelected() == true) {
                Tipo = "R";
                Cliente Cliente = new Cliente(Nombre, Correo, Tipo, Ventanilla, NumeroDeCliente, Celular);
                Ventana.ColaR.enqueue(Cliente);
                numeroR++;
                if (NumeroDeCliente == 99) {
                    NumeroDeCliente = 0;
                } else {
                    NumeroDeCliente++;
                }
                RegularCheck.setSelected(false);
                //SendMailTLS Mensaje = new SendMailTLS(Cliente.Celular, Cliente.Code);
                //Mensaje.Tiquete();
            } else if (CorporativoCheck.isSelected() == true) {
                Tipo = "C";
                Cliente Cliente = new Cliente(Nombre, Correo, Tipo, Ventanilla, NumeroDeCliente, Celular);
                Ventana.ColaC.enqueue(Cliente);
                numeroC++;
                if (NumeroDeCliente == 99) {
                    NumeroDeCliente = 0;
                } else {
                    NumeroDeCliente++;
                }
                CorporativoCheck.setSelected(false);
                //SendMailTLS Mensaje = new SendMailTLS(Cliente.Celular, Cliente.Code);
                //Mensaje.Tiquete();
            } else if (EmbarazadaCheck.isSelected() == true) {
                Tipo = "E";
                Cliente Cliente = new Cliente(Nombre, Correo, Tipo, Ventanilla, NumeroDeCliente, Celular);
                Ventana.ColaE.enqueue(Cliente);
                numeroE++;
                if (NumeroDeCliente == 99) {
                    NumeroDeCliente = 0;
                } else {
                    NumeroDeCliente++;
                }
                EmbarazadaCheck.setSelected(false);
                //SendMailTLS Mensaje = new SendMailTLS(Cliente.Celular, Cliente.Code);
                //Mensaje.Tiquete();
            } else if (MayorCheck.isSelected() == true) {
                Tipo = "M";
                Cliente Cliente = new Cliente(Nombre, Correo, Tipo, Ventanilla, NumeroDeCliente, Celular);
                Ventana.ColaM.enqueue(Cliente);
                numeroM++;
                if (NumeroDeCliente == 99) {
                    NumeroDeCliente = 0;
                } else {
                    NumeroDeCliente++;
                }
                MayorCheck.setSelected(false);
                //SendMailTLS Mensaje = new SendMailTLS(Cliente.Celular, Cliente.Code);
                //Mensaje.Tiquete();
            } else if (DiscapacitadoCheck.isSelected() == true) {
                Tipo = "D";
                Cliente Cliente = new Cliente(Nombre, Correo, Tipo, Ventanilla, NumeroDeCliente, Celular);
                Ventana.ColaD.enqueue(Cliente);
                numeroD++;
                if (NumeroDeCliente == 99) {
                    NumeroDeCliente = 0;
                } else {
                    NumeroDeCliente++;
                }
                DiscapacitadoCheck.setSelected(false);
                //SendMailTLS Mensaje = new SendMailTLS(Cliente.Celular, Cliente.Code);
                //Mensaje.Tiquete();
            }
            TextNombre.setText(null);
            TextCorreo.setText(null);
            txtCel.setText(null);

            JOptionPane.showOptionDialog(this, "Su codigo es: " + Cliente.Code, "Su Codigo", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "}, "OK");
        }

    }//GEN-LAST:event_AceptarQuioscoActionPerformed

    private void TipoVentanillaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoVentanillaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoVentanillaComboBoxActionPerformed

    public static int NumeroDeCliente = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarQuiosco;
    private javax.swing.JRadioButton CorporativoCheck;
    private javax.swing.JRadioButton DiscapacitadoCheck;
    private javax.swing.JRadioButton EmbarazadaCheck;
    private javax.swing.JRadioButton MayorCheck;
    private javax.swing.JRadioButton RegularCheck;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextNombre;
    public static javax.swing.JComboBox TipoVentanillaComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCel;
    // End of variables declaration//GEN-END:variables
}
